[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = postgres
db_port = 5432
db_user = odoo
db_password = %(POSTGRES_PASSWORD)s
db_name = giraffos_sii
db_filter = ^giraffos_sii$
admin_passwd = %(ODOO_ADMIN_PASSWORD)s
without_demo = True
log_level = info
log_handler = odoo.modules.loading:DEBUG
longpolling_port = 8072
workers = 2
max_cron_threads = 1
list_db = False
proxy_mode = True
