[options]
addons_path = /mnt/extra-addons,/opt/oca/payroll,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = postgres
db_port = 5432
db_user = odoo
db_password = cuentax_odoo
db_name = cuentax_odoo
db_filter = ^cuentax_odoo$
admin_passwd = cuentax_master_2026
without_demo = True
log_level = info
log_handler = odoo.modules.loading:DEBUG
longpolling_port = 8072
workers = 2
max_cron_threads = 1
list_db = False
proxy_mode = False
