/**
 * CUENTAX — 1099-NEC PDF (Summary sheet, not the official IRS form)
 * ====================================================================
 * Produces a US 1099-NEC information summary for a given year. Lists every
 * vendor paid ≥ $600 with their tax-year total. Users should file the
 * actual IRS form separately — this is a bookkeeping support document.
 *
 * Each page includes:
 *   - Payer (company) name, EIN, address
 *   - Recipient (vendor) block
 *   - Box 1: Nonemployee compensation (total paid this year)
 *   - Instructions footer
 */

import PDFDocument from 'pdfkit'
import { buildYearSummary } from './bank-reconciliation.service'

export interface Vendor1099Entry {
  vendor: string
  total: number
  count: number
}

export interface Form1099Data {
  company_name: string
  company_tax_id: string
  company_address?: string
  year: number
  vendors: Vendor1099Entry[]
  threshold: number
}

export function generate1099Pdf(data: Form1099Data): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'LETTER', margins: { top: 50, bottom: 50, left: 50, right: 50 } })
      const chunks: Buffer[] = []
      doc.on('data', (c) => chunks.push(c))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      // Cover sheet
      doc.font('Helvetica-Bold').fontSize(18).fillColor('#000').text('Form 1099-NEC Summary', { align: 'center' })
      doc.font('Helvetica').fontSize(9).fillColor('#666').text('Nonemployee Compensation — Tax Year ' + data.year, { align: 'center' })
      doc.moveDown(0.5)
      doc.fontSize(11).fillColor('#333').text(`Payer: ${data.company_name}`, { align: 'center' })
      doc.fontSize(8).fillColor('#888').text(`EIN: ${data.company_tax_id || '—'}`, { align: 'center' })
      if (data.company_address) {
        doc.text(data.company_address, { align: 'center' })
      }
      doc.moveDown(1)
      doc.fontSize(8).fillColor('#666').text(
        `This summary lists vendors paid $${data.threshold.toFixed(2)} or more during ${data.year}. ` +
        `Use these figures to file Form 1099-NEC for each recipient with the IRS. ` +
        `This document is for internal use only and is NOT the official IRS form.`,
        { align: 'center' },
      )
      doc.moveDown(1)

      // Table header
      doc.strokeColor('#333').lineWidth(1).moveTo(50, doc.y).lineTo(562, doc.y).stroke()
      doc.moveDown(0.3)
      doc.font('Helvetica-Bold').fontSize(9).fillColor('#333')
      const y0 = doc.y
      doc.text('Recipient / Vendor', 50, y0, { width: 300 })
      doc.text('Payments',           50, y0, { width: 512, align: 'right' })
      doc.moveDown(0.2)
      doc.strokeColor('#999').lineWidth(0.5).moveTo(50, doc.y).lineTo(562, doc.y).stroke()
      doc.moveDown(0.1)

      // Rows
      doc.font('Helvetica').fontSize(10).fillColor('#333')
      if (data.vendors.length === 0) {
        doc.fillColor('#999').text('  No vendors above the threshold.', 50, doc.y)
        doc.moveDown(0.4)
      } else {
        for (const v of data.vendors) {
          if (doc.y > 690) doc.addPage()
          const y = doc.y
          doc.fillColor('#333').text(v.vendor.slice(0, 50), 50, y, { width: 350 })
          doc.fillColor('#0a5f2d').text(`$${v.total.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
                                        50, y, { width: 512, align: 'right' })
          doc.fillColor('#aaa').fontSize(8).text(`${v.count} transactions`, 50, y, { width: 512, align: 'right' })
          doc.fontSize(10).fillColor('#333')
          doc.moveDown(0.3)
        }
      }

      // Total
      doc.moveDown(0.3)
      doc.strokeColor('#000').lineWidth(1.5).moveTo(50, doc.y).lineTo(562, doc.y).stroke()
      doc.moveDown(0.3)
      const total = data.vendors.reduce((s, v) => s + v.total, 0)
      doc.font('Helvetica-Bold').fontSize(12).fillColor('#000')
      const yT = doc.y
      doc.text('TOTAL', 50, yT, { width: 350 })
      doc.text(`$${total.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 50, yT, { width: 512, align: 'right' })

      // Footer
      doc.moveDown(3)
      doc.font('Helvetica').fontSize(7).fillColor('#aaa').text(
        'Generated by CuentaX. For US tax compliance support only. File the official IRS Form 1099-NEC separately.',
        { align: 'center' },
      )

      doc.end()
    } catch (err) { reject(err) }
  })
}

/**
 * Convenience: build the Vendor1099Entry[] from our year summary data.
 */
export async function build1099Entries(
  companyId: number,
  year: number,
  threshold: number = 600,
): Promise<Vendor1099Entry[]> {
  const summary = await buildYearSummary(companyId, year, 'USD')
  return summary.top_vendors_by_spend
    .filter(v => v.total >= threshold)
    .map(v => ({ vendor: v.vendor, total: v.total, count: v.count }))
}
